# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 16:21
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('Betatester', 'Betatester'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], max_length=40)),
                ('observations', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], max_length=40)),
                ('platform', models.CharField(blank=True, choices=[('gazebo', 'Gazebo'), ('websim', 'WebSim'), ('real', 'Real'), ('theory', 'Theory'), ('vision', 'Vision'), ('tutorials', 'Tutoriales')], max_length=40)),
                ('language', models.CharField(choices=[('python', 'Python'), ('scratch', 'Scratch'), ('javascript', 'JavaScript')], max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('video', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.CharField(blank=True, max_length=100)),
                ('assets', models.CharField(default=b'{"notebook": ""}', max_length=2000)),
                ('gui', models.CharField(blank=True, max_length=2000)),
                ('referee', models.CharField(blank=True, max_length=2000)),
                ('real', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('main_server', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('max_simulations', models.IntegerField(default=0)),
                ('running_simulations', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('cpu_limit', models.FloatField(default=1.5)),
                ('memory_limit', models.CharField(default='1g', max_length=15)),
                ('uc_equivalence', models.FloatField(default=3.5)),
                ('compute_load', models.IntegerField(default=0)),
                ('compute_capacity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('observations', models.TextField(blank=True, max_length=500)),
                ('exercises', models.ManyToManyField(to='jderobot_kids.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_admin', 'admin'), ('is_profesor', 'profesor'), ('is_alumno', 'alumno')),
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('init_simulation', models.CharField(max_length=200)),
                ('simulation_type', models.CharField(max_length=200)),
                ('exercise', models.CharField(max_length=200)),
                ('docker_id', models.CharField(max_length=200)),
                ('client_ip', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=200)),
                ('ws_channel', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='packs',
            field=models.ManyToManyField(blank=True, to='jderobot_kids.Pack'),
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.ManyToManyField(blank=True, to='jderobot_kids.Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='jderobot_kids.Exercise'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='packs',
            field=models.ManyToManyField(blank=True, to='jderobot_kids.Pack'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
