# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jderobot_kids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='compute_load',
            field=models.IntegerField(default=100),
        ),
    ]
