# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-08 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jderobot_kids.models


class Migration(migrations.Migration):

    dependencies = [
        ('jderobot_kids', '0002_exercise_compute_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('form_pic', models.ImageField(blank=True, default='', upload_to='blog/')),
                ('post_video', models.CharField(blank=True, default='', max_length=100)),
                ('categories', models.ManyToManyField(related_name='posts', to='jderobot_kids.Category')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='anonymous_avatar.png', upload_to=jderobot_kids.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jderobot_kids.Post'),
        ),
    ]
