# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-20 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jderobot_kids', '0006_auto_20191217_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='platform',
            field=models.CharField(blank=True, choices=[('gazebo', 'Gazebo'), ('websim', 'WebSim'), ('pyonbrowser-theory', 'PyOnBrowser Theory'), ('real', 'Real'), ('real-jupyter', 'Real-Jupyter'), ('theory', 'Theory'), ('vision', 'Vision'), ('tutorials', 'Tutoriales')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 11, 45, 29, 819774)),
        ),
    ]
