# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-05 11:37
from __future__ import unicode_literals

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jderobot_kids', '0007_auto_20200120_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='compute_capacity',
        ),
        migrations.RemoveField(
            model_name='host',
            name='compute_load',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu_limit',
        ),
        migrations.RemoveField(
            model_name='host',
            name='max_simulations',
        ),
        migrations.RemoveField(
            model_name='host',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='host',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='host',
            name='running_simulations',
        ),
        migrations.RemoveField(
            model_name='host',
            name='uc_equivalence',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='docker_id',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='assets',
            field=models.CharField(default='{"notebook": ""}', max_length=2000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('scratch', 'Scratch'), ('python', 'Python'), ('javascript', 'JavaScript')], max_length=40),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='platform',
            field=models.CharField(blank=True, choices=[('websim', 'WebSim'), ('pyonbrowser-theory', 'PyOnBrowser Theory'), ('real', 'Real'), ('real-jupyter', 'Real-Jupyter'), ('theory', 'Theory'), ('vision', 'Vision'), ('tutorials', 'Tutoriales')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 12, 37, 38, 932917)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
