# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jderobot_kids', '0008_auto_20200205_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='promotional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='platform',
            field=models.CharField(blank=True, choices=[('websim', 'WebSim'), ('pyonbrowser-theory', 'PyOnBrowser Theory'), ('real', 'Real')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 14, 30, 52, 848391)),
        ),
    ]
