# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-30 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jderobot_kids', '0009_auto_20200217_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('challenge', 'Challenge'), ('shared_game', 'Shared game'), ('webIDE', 'WebIDE')], max_length=40),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('scratch', 'Scratch')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 23, 17, 55, 671328)),
        ),
    ]
